export const DataProduct = [
    {
      id: 1,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-12-mini.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 2,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-12-pro--.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 3,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-12-pro-max-.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 4,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-12.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 5,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-13-mini.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 6,
      image: "/designImage/imageProducts/Mobile Devices/Smartphones/apple-iphone-13-pro-max.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 7,
      image: "/designImage/imageProducts/Mobile Devices/Tablets/apple-ipad-air-11-2024.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 8,
      image: "/designImage/imageProducts/Mobile Devices/Tablets/apple-ipad-air-13-2024.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 9,
      image: "/designImage/imageProducts/Mobile Devices/Tablets/apple-ipad-pro-11-2024.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    {
      id: 10,
      image: "/designImage/imageProducts/Mobile Devices/Tablets/apple-ipad-pro-13-2024.jpg",
      name: "product name...",
      sale: 100.0,
      price: 12000000,
      discount: 10,
    },
    
  ];